edition = "2018"
max_width = 80
reorder_imports = true
reorder_impl_items = true
binop_separator = "Back"
blank_lines_lower_bound = 0
enum_discrim_align_threshold = 20
error_on_unformatted = true
fn_args_layout = "Vertical"
format_code_in_doc_comments = true
format_strings = true
imports_layout = "Vertical"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true 
report_fixme = "Always"
report_todo = "Always"
struct_field_align_threshold = 20
wrap_comments = true
